### ISSUE TITLE
DevTools failed to parse SourceMap: performance-now.js.map

### ISSUE THREAD

**Issue by trevordmiller** [myrne/performance-now#18]
I'm getting a console warning:
![image](https://user-images.githubusercontent.com/5497885/30458924-061692cc-996b-11e7-80ef-73e83595c27c.png)

And the only reference I can find to this is in this package:

![image](https://user-images.githubusercontent.com/5497885/30458893-e353192c-996a-11e7-9b7e-bb23ae6cd038.png)

It seems to me that the `# sourceMappingURL=performance-now.js.map` line needs to point to an absolute path, not a relative path (which doesn't exist when being consumed as a library via npm in another package)?

Thank you.

**Comment by sppatel** [comment]
I am seeing this as well.

**Comment by trevordmiller** [comment]
This went away for me in latest dependency upgrades. Closing.
